# Generated by Django 2.2.7 on 2019-12-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name_plural': 'ToDo'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='head',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
