# Generated by Django 2.2.7 on 2019-12-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doapp', '0002_auto_20191215_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo',
            field=models.TextField(null=True),
        ),
    ]
